let allDataObj = [
    {
        id : 0,
        name : '커피숍',
        nametype : 'K',
        subname : 'Coffee Shop',
        Language : ['HTML',', SCSS',', JavaScript',', React',', Bootstrap',', Redux'],
        content : 'Redux를 활용한 커피숍 프로젝트입니다. 메뉴 더보기를 누르면 JSON파일에서 추가 정보를 가져오며 메뉴 정렬 및 카테고리 분류가 가능합니다. MENU에서는 ‘ADD TO CART’를 누르면 누를때마다 장바구니에 상품이 담기고 상품을 직접 클릭했을때는 상품 상세페이지로 이동됩니다. 홈 화면에서 받은 쿠폰은 사용자에게 저장되어 장바구니에서 조건별로 적용가능합니다.',
        colorcode : ['#955427','#232325'],
        composition : ['메인페이지', ', 서브페이지(Nav전체, 상품페이지)'],
        features : ['풀페이지(홈)',', Axios',', 정렬 및 분류',', CART',', 쿠폰적용'],
        imagesPC : '/img/COFFEE SHOP/Pc.png', 
        imagesTB : '/img/COFFEE SHOP/Tb.png', 
        imagesMB : '/img/COFFEE SHOP/Mb.png', 
        weblink : 'https://jjh1129jh.github.io/CoffeeShop/',
        bgcolor : '#4b3322',
        textcolor : 'rgb(238, 238, 238)'
    },
    {
        id : 1,
        name : '스냅클라우드',
        nametype : 'K',
        subname : 'Snap Cloud',
        Language : ['HTML',', SCSS',', JavaScript',', React',', Bootstrap'],
        content : '새롭게 React언어를 적용하여 사진 커뮤니티를 만들었습니다. 이미지를 업로드하면 이미지 정보가 서버에 저장되면서 포스트가 업로드되고 포스트에 좋아요를 누르거나 댓글을 작성할수있습니다.',
        colorcode : ['#629fd6','#dadada'],
        composition : ['메인페이지',', 팝업페이지'],
        features : ['글 업로드 및 삭제',', 댓글 작성 및 삭제',', 인기포스트 표시'],
        imagesPC : '/img/SNAPCLOUD/Pc.png', 
        imagesTB : '/img/SNAPCLOUD/Tb.png', 
        imagesMB : '/img/SNAPCLOUD/Mb.png', 
        weblink : 'https://jjh1129jh.github.io/SnapCloud/',
        bgcolor : 'lightslategrey',
        textcolor : 'rgb(238, 238, 238)'
    },
    {
        id : 2,
        name : 'KFC',
        nametype : 'E',
        subname : 'Kentucky Fried Chicken',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '기존 KFC 홈페이지에서 주요 메뉴 위주의 풀페이지 구성으로 심플하게 구성하여 누구나 접근하기 쉽게 구성해보았습니다.',
        colorcode : ['#ea0a2a','#9a1e29','#ff7800'],
        composition : ['메인페이지'],
        features : ['풀페이지',', 오브젝트 애니메이션'],
        imagesPC : '/img/KFC/KFCfull.jpg', 
        imagesTB : '/img/KFC/ipad.png', 
        imagesMB : '/img/KFC/mobile.png', 
        weblink : 'https://jjh1129jh.github.io/kfc/',
        bgcolor : '#9c1621',
        textcolor : 'rgb(238, 238, 238)'
    },
    {
        id : 3,
        name : '이란 관광청',
        nametype : 'K',
        subname : 'YILAN Tourism Office',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '자작 홈페이지입니다. 코로나 시국이 끝나면 대만에 있는 이란이라는 도시에 놀러가자는 친구의 말에 흥미를 갖게 되어 제작해보았습니다.',
        colorcode : ['#d19d65','#fcfcfc'],
        composition : ['메인페이지',', 서브페이지(TOUR, HOTEL, FOOD)'],
        features : ['Auto 슬라이드',', 스와이퍼',', API 연동(구글맵스, 이미지뷰어)'],
        imagesPC : '/img/YILAN/pc.png', 
        imagesTB : '/img/YILAN/IPAD.png', 
        imagesMB : '/img/YILAN/mobile.png', 
        weblink : 'https://jjh1129jh.github.io/yilan/',
        bgcolor : '#576954',
        textcolor : 'rgb(238, 238, 238)'
    },
    {
        id : 4,
        name : 'NIKON',
        nametype : 'E',
        subname : 'Nikon Imaging Korea',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '니콘 홈페이지를 경쟁업체중 하나인 라이카의 스타일로 재구성 하였습니다. 대표색인 노란색로 포인트를 주었습니다.',
        colorcode : ['#ffe600','#000000','#f3f3f3'],
        composition : ['메인페이지',', 서브페이지(LOGIN)'],
        features : ['Auto 슬라이드'],
        imagesPC : '/img/NIKON/Pc.png', 
        imagesTB : '', 
        imagesMB : '/img/NIKON/Mobile.png', 
        weblink : 'https://jjh1129jh.github.io/nikon/',
        bgcolor : '#353535',
        textcolor : '#4b4b4b'
    },
    {
        id : 5,
        name : '동방',
        nametype : 'K',
        subname : 'Dong Bang',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '기존 홈페이지는 제작한지 오래되어 고전적 스타일로 구성되어 있습니다. 동종 업종의 홈페이지를 참고하여 리뉴얼 하였습니다.',
        colorcode : ['#1b3052','#303030'],
        composition : ['메인페이지',', 서브페이지(LOGIN, JOIN)'],
        features : ['-'],
        imagesPC : '/img/DONGBANG/Pc.png', 
        imagesTB : '', 
        imagesMB : '', 
        weblink : 'https://jjh1129jh.github.io/dongbang/',
        bgcolor : '#131538',
        textcolor : 'hsla(0, 0%, 93%, 1.00)'
    },
    {
        id : 6,
        name : '포트폴리오',
        nametype : 'K',
        subname : 'PORTFOLIO',
        Language : ['HTML',', SCSS',', JavaScript',', React'],
        content : '정지환의 포트폴리오 홈페이지 입니다.',
        colorcode : ['#dfb475','#575757'],
        composition : ['메인페이지'],
        features : ['풀페이지',', 스와이퍼'],
        imagesPC : '/img/PORTFOLIO/Pc.png', 
        imagesTB : '/img/PORTFOLIO/Tb.png', 
        imagesMB : '/img/PORTFOLIO/Mb.png', 
        weblink : '',
        bgcolor : '#adadad',
        textcolor : 'rgb(238, 238, 238)'
    },
]

let allDataObj2 = [
    {
        id : 0,
        name : '쉐보레 콜로라도',
        nametype : 'K',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '쉐보레의 콜로라도가 25년 새로운 모델로 출시되면서 그에 맞춰 진행된 프로젝트입니다. 디지털 브로슈어형태로 제작되었으며. 외부와 내부의 구성을 볼수있고 차량 색상변경, PDF다운로드 등을 제공합니다.',
        contribution : '★★★★★',
        participants : '3명',
        responsibilities : '개발 및 디자인',
        images : '/img/PROJECT/Capture10.png', 
        weblink : ['https://jjh1129jh.github.io/colorado'],
        linktype : 'F',
        bgcolor : '#353535',
        objcolor : '#e3ba4e'
    },
    {
        id : 1,
        name : '지학사 미술과정',
        nametype : 'K',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '디지털 교과서 타입으로 진행한 프로젝트입니다. 교과서처럼 페이지를 넘길수있고 특정 스팟을 누르면 세부적인 교육내용 (읽기, 클릭, 퀴즈, 영상보기)등을 제공합니다.',
        contribution : '★★★★★',
        participants : '3명',
        responsibilities : '프로토타입 개발 및 양산',
        images : '/img/PROJECT/Capture11.png', 
        weblink : ['https://jjh1129jh.github.io/art4/arte4.html'],
        linktype : 'F',
        bgcolor : '#9b9372ff',
        objcolor : '#f05a94'
    },
    {
        id : 2,
        name : '코오롱 2024 윤리경영 과정',
        nametype : 'K',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '코오롱에서 24년 직원들에게 윤리경영 과정 교육을 위해 진행한 프로젝트입니다. 게임적인 요소들을 많이 넣어달라고 요청을 받아서 전체적인 틀은 드래곤을 잡으러 가는 용사 컨셉을 잡았고 교육영상 중간중간에 인터렉티브 요소로 넣어 레벨업을 하고 최종적으론 모든 아이템을 모아 드래곤을 잡으러 가게됩니다. 샘플은 전체적인흐름을 볼수있는 풀콘텐츠, 양방향 클릭형 선긋기, 애니메이션식 퀴즈, 떨어지는 물건 상자에 받기로 구성하였습니다.',
        contribution : '★★★★★',
        participants : '5명 +',
        responsibilities : '프로토타입 개발 및 양산',
        images : '/img/PROJECT/Capture9.png', 
        weblink : ['https://jjh1129jh.github.io/kolon/03/03_01.html','https://jjh1129jh.github.io/integrated/02/group1/02/02_04.html','https://jjh1129jh.github.io/integrated/02/group1/02/02_03.html','https://jjh1129jh.github.io/integrated/02/group2/03/03_04.html'],
        linktype : 'W',
        bgcolor : '#9c1621',
        objcolor : 'coral'
    },
    {
        id : 3,
        name : '제안용 샘플 콘텐츠',
        nametype : 'K',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '사측의 요청으로 만든 제안용 샘플중 일부입니다. 단어 완성하기, 낱말퀴즈 풀기, 특정시간 북마크좌표 찍기, 360도 회전영상 전환 으로 구성하였습니다.',
        contribution : '★★★★★',
        participants : '2명',
        responsibilities : '개발 및 디자인',
        images : '/img/PROJECT/Capture8.png', 
        weblink : ['https://jjh1129jh.github.io/integrated/01/01/01_01.html','https://jjh1129jh.github.io/integrated/01/04/04_01.html','https://jjh1129jh.github.io/integrated/01/03/03_01.html','https://jjh1129jh.github.io/integrated/01/03/03_02.html'],
        linktype : 'W',
        bgcolor : '#66687eff',
        objcolor : '#325175ff'
    },
    {
        id : 4,
        name : '영상 검수 프로그램',
        nametype : 'K',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '직원들의 요청으로 영상 검수 프로그램을 제작했습니다. 영상을 선택하고 검수자의 이름을 적은 뒤 팀별로 정해진 버튼을 클릭하면 서로 다른색의 사각형을 영상 위에 그릴수있습니다. 영상의 특정부분에 사각형을 그리고 요청사항을 입력한뒤에 캡쳐를 누르면 캡쳐가 로컬로 저장이 되는데 모든 캡쳐가 끝났다면 PPT 내보내기를 눌러서 그동안 저장된 캡쳐들을 정리한 파워포인트 파일을 만들어 공유할수있게 하였습니다.',
        contribution : '★★★★★',
        participants : '1명',
        responsibilities : '단독 프로젝트',
        images : '/img/PROJECT/Capture7.png', 
        weblink : ['https://jjh1129jh.github.io/inspection'],
        linktype : 'F',
        bgcolor : '#8294a8ff',
        objcolor : '#4a88d4ff'
    },
    {
        id : 5,
        name : '대구한의대학교 VR 튜토리얼',
        nametype : 'K',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '대구한의대학교 VR교육을 위한 콘텐츠입니다. VR시뮬레이션, VR기기에 대한 리뷰 영상을 포함하고있고, 클라이언트의 요청으로 360도 인체모형 모델을 추가했습니다. 마지막으로 메뉴얼버튼 클릭 시 VR기기 제조사 메뉴얼 페이지로 이동합니다.',
        contribution : '★★★★★',
        participants : '2명',
        responsibilities : '개발 및 디자인',
        images : '/img/PROJECT/Capture6.png', 
        weblink : ['https://jjh1129jh.github.io/daeguhanui/01/01_01.html'],
        linktype : 'W',
        bgcolor : '#19363c',
        objcolor : '#269da9'
    },
    {
        id : 6,
        name : '서울신문 계절의 실종',
        nametype : 'K',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '온난화로 인한 이상기후에 대해 알려주는 콘텐츠입니다. 세계지도에 연도별 버튼을 두어 이상기후 사례를 확인할수있고 식물 선호 테스트를 통해 나에게 맞는 식물찾기 기능이 있습니다. 그 밖에 이상기후에 관한 영상을 제공하고있습니다.',
        contribution : '★★★★★',
        participants : '2명',
        responsibilities : '개발 및 디자인',
        images : '/img/PROJECT/Capture5.png', 
        weblink : ['https://jjh1129jh.github.io/garden/01/01_01.html'],
        linktype : 'W',
        bgcolor : '#435536ff',
        objcolor : '#006b5f'
    },
    {
        id : 7,
        name : '한국교육학술정보원 KERIS 개발',
        nametype : 'K',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '개발도상국 국가들에 무료로 제공하는 초등, 중등 한국어 교육 과정입니다. 총 5개국어 자막과 음성안내가 지원됩니다. AI업체와 협업한 음성인식, 필기인식 기능이 대표적이며 그 외에도 퀴즈, 타이핑, 드래그드롭 등을 구현했습니다. 방대한 교육과정으로 인해 HTML소스에는 공통코드만 넣어주고 JS로 실행과 동시에 각각의 콘텐츠가 추가되게 하였습니다.',
        contribution : '★★★★★',
        participants : '18명 +',
        responsibilities : '프로토타입 개발 및 양산',
        images : '/img/PROJECT/Capture4.png', 
        weblink : ['/keris/01/01.html','/keris/02/01.html','/keris/03/01.html','/keris/04/01.html'],
        linktype : 'W',
        bgcolor : '#627fa0',
        objcolor : '#64a9fb'
    },
    {
        id : 8,
        name : '국립외교원',
        nametype : 'K',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '영상 기반 교육컨텐츠입니다. 자사에서 운영하던 기존 e러닝 영상플레이어에 부가기능 (자막, 전체화면, 배속, 다운로드) 기능을 더하면서 레이아웃을 수정하였고 720p 고정 사이즈 플레이어를 여러 환경에서의 원할한 수강을 위해 반응형으로 수정하였습니다.',
        contribution : '★★★★★',
        participants : '4명 +',
        responsibilities : '프로토타입 개발 및 양산',
        images : '/img/PROJECT/Capture3.png', 
        weblink : [],
        linktype : 'W',
        bgcolor : '#afa496',
        objcolor : '#6f4620'
    },
    {
        id : 9,
        name : '삼육보건대학교',
        nametype : 'K',
        Language : ['HTML',', SCSS',', JavaScript',', jQuery'],
        content : '2019년부터 진행된 서비스를 인수인계 받아 유지보수를 진행하였고 2023년엔 과목 개설을 위한 개발을 진행하기도 했습니다.',
        contribution : '★★★☆☆',
        participants : '3명',
        responsibilities : '유지보수 및 양산',
        images : '/img/PROJECT/Capture2.png', 
        weblink : [],
        linktype : 'W',
        bgcolor : '#7f9ec0',
        objcolor : '#a5cae7'
    },
    {
        id : 10,
        name : '경상대학교 전자책',
        nametype : 'K',
        Language : ['HTML',', SCSS',', jQuery'],
        content : 'Epub방식을 채택한 e북형식 교재입니다. 경상대학교 LMS에서 제공하는 프로그램으로 모바일기기, PC에서 책을 읽듯이 학습이 가능합니다. epub 전용 제작 프로그램 자체기능 중 지원하지 않는 (확대, 팝업) 은 jquery 언어를 사용하여 추가했습니다.',
        contribution : '★★★★☆',
        participants : '4명',
        responsibilities : '프로토타입 개발 및 양산',
        images : '/img/PROJECT/Capture1.png', 
        weblink : [],
        linktype : 'W',
        bgcolor : '#2e0e4d',
        objcolor : '#82659e'
    },
]

export {allDataObj ,allDataObj2};
