// 1배열 : 한국어, 2배열 : 영어, 3배열 : 중국어, 4배열 : 베트남어, 5배열 : 러시아어, 6배열 : 캄보디아어

var totalLanguage = [
	[
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
	],
	[
		["Look at the picture and choose the correct one from the list."],
		["Look at the picture and choose the correct one from the list."],
		["Look at the picture and choose the correct one from the list."],
		["Look at the picture and choose the correct one from the list."],
		["Look at the picture and choose the correct one from the list."],
		["Look at the picture and choose the correct one from the list."],
		["Look at the picture and choose the correct one from the list."],
		["Look at the picture and choose the correct one from the list."],
	],
	[
		["看图片，在<例子>中选择合适的。"],
		["看图片，在<例子>中选择合适的。"],
		["看图片，在<例子>中选择合适的。"],
		["看图片，在<例子>中选择合适的。"],
		["看图片，在<例子>中选择合适的。"],
		["看图片，在<例子>中选择合适的。"],
		["看图片，在<例子>中选择合适的。"],
		["看图片，在<例子>中选择合适的。"],
	],
	[
		["Nhìn tranh và chọn đáp án đúng ở &lt;mẫu&gt;."],
		["Nhìn tranh và chọn đáp án đúng ở &lt;mẫu&gt;."],
		["Nhìn tranh và chọn đáp án đúng ở &lt;mẫu&gt;."],
		["Nhìn tranh và chọn đáp án đúng ở &lt;mẫu&gt;."],
		["Nhìn tranh và chọn đáp án đúng ở &lt;mẫu&gt;."],
		["Nhìn tranh và chọn đáp án đúng ở &lt;mẫu&gt;."],
		["Nhìn tranh và chọn đáp án đúng ở &lt;mẫu&gt;."],
		["Nhìn tranh và chọn đáp án đúng ở &lt;mẫu&gt;."],
	],
	[
		["Посмотрите на картинку и выберите нужную из примера."],
		["Посмотрите на картинку и выберите нужную из примера."],
		["Посмотрите на картинку и выберите нужную из примера."],
		["Посмотрите на картинку и выберите нужную из примера."],
		["Посмотрите на картинку и выберите нужную из примера."],
		["Посмотрите на картинку и выберите нужную из примера."],
		["Посмотрите на картинку и выберите нужную из примера."],
		["Посмотрите на картинку и выберите нужную из примера."],
	],
	[
		["សូមមើលរូប រួចជ្រើសរើសចម្លើយដែលត្រឹមត្រូវដូចនឹង <ឧទាហរណ៍>។"],
		["សូមមើលរូប រួចជ្រើសរើសចម្លើយដែលត្រឹមត្រូវដូចនឹង <ឧទាហរណ៍>។"],
		["សូមមើលរូប រួចជ្រើសរើសចម្លើយដែលត្រឹមត្រូវដូចនឹង <ឧទាហរណ៍>។"],
		["សូមមើលរូប រួចជ្រើសរើសចម្លើយដែលត្រឹមត្រូវដូចនឹង <ឧទាហរណ៍>។"],
		["សូមមើលរូប រួចជ្រើសរើសចម្លើយដែលត្រឹមត្រូវដូចនឹង <ឧទាហរណ៍>។"],
		["សូមមើលរូប រួចជ្រើសរើសចម្លើយដែលត្រឹមត្រូវដូចនឹង <ឧទាហរណ៍>។"],
		["សូមមើលរូប រួចជ្រើសរើសចម្លើយដែលត្រឹមត្រូវដូចនឹង <ឧទាហរណ៍>។"],
		["សូមមើលរូប រួចជ្រើសរើសចម្លើយដែលត្រឹមត្រូវដូចនឹង <ឧទាហរណ៍>។"],
	]
]